Importing the dependencies

In [114]:
import pandas as pd
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

In [115]:
# importing the model
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [116]:
heart_data = pd.read_csv("/content/heart.csv")

In [117]:
heart_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [118]:
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [119]:
heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [120]:
heart_data['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

In [121]:
heart_data.shape

(303, 14)

Spliting in feature and target

In [122]:
x = heart_data.drop(columns = 'target', axis=1)
y = heart_data['target']

In [123]:
print(x.shape, y.shape)

(303, 13) (303,)

In [124]:
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [125]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [126]:
x = np.asarray(x)
y = np.asarray(y)

Model Selection

     1. Comparing the models with default hyperparameter values using Cross Validation

In [127]:
models = [LogisticRegression(max_iter=10000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier(random_state=0)]

In [128]:
def compare_models_cross_validation():

  for model in models:

    cv_score = cross_val_score(model, x, y, cv=5) * 100
    mean_accuracy = np.mean(cv_score) 
    mean_accuracy = round(mean_accuracy, 2)
    print('Cross Validation accuracies for the', model, '=', cv_score)
    print('Accuracy score of the', model, '=', mean_accuracy,'%')
    print("------------------------------------------------------------------------------------------------")

In [129]:
compare_models_cross_validation()

Cross Validation accuracies for the LogisticRegression(max_iter=10000) = [80.32786885 86.8852459  85.24590164 86.66666667 75.        ]
Accuracy score of the LogisticRegression(max_iter=10000) = 82.83 %
------------------------------------------------------------------------------------------------
Cross Validation accuracies for the SVC(kernel='linear') = [81.96721311 88.52459016 80.32786885 86.66666667 76.66666667]
Accuracy score of the SVC(kernel='linear') = 82.83 %
------------------------------------------------------------------------------------------------
Cross Validation accuracies for the KNeighborsClassifier() = [60.6557377  65.57377049 57.37704918 73.33333333 65.        ]
Accuracy score of the KNeighborsClassifier() = 64.39 %
------------------------------------------------------------------------------------------------
Cross Validation accuracies for the RandomForestClassifier(random_state=0) = [85.24590164 90.16393443 81.96721311 81.66666667 80.        ]
Accuracy score of the RandomForestClassifier(random_state=0) = 83.81 %
------------------------------------------------------------------------------------------------

Inference: for the Heart Disease dataset, **Random Forest Classifier** has the Highest accuracy value with default hyperparameter values

    2. Comparing the models with different Hyperparameter values using GridSeachCV

In [130]:
# list of models
models_list = [LogisticRegression(max_iter=10000), SVC(), KNeighborsClassifier(), RandomForestClassifier(random_state=0)]

In [131]:
# creating a dictionary that contains hyperparameter values for the above mentioned models

model_hyperparameters = {
    
    'log_reg_hyperparameters': {'C' : [1,5,10,20]},

    'svc_hyperparameters': {'kernel' : ['linear','poly','rbf','sigmoid'],'C' : [1,5,10,20]},

    'KNN_hyperparameters' : {'n_neighbors' : [3,5,10]},

    'random_forest_hyperparameters' : {'n_estimators' : [10, 20, 50, 100]}
}

In [132]:
model_hyperparameters.keys()

dict_keys(['log_reg_hyperparameters', 'svc_hyperparameters', 'KNN_hyperparameters', 'random_forest_hyperparameters'])

In [133]:
model_hyperparameters.values()

dict_values([{'C': [1, 5, 10, 20]}, {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}, {'n_neighbors': [3, 5, 10]}, {'n_estimators': [10, 20, 50, 100]}])

In [134]:
models_keys = list(model_hyperparameters.keys())
models_keys

['log_reg_hyperparameters',
 'svc_hyperparameters',
 'KNN_hyperparameters',
 'random_forest_hyperparameters']

Applying GridSearchCV

In [135]:
def ModelSelection(list_of_models, hyperparameters_dictionary):

  result = []
  i = 0
  for model in list_of_models:

    key = models_keys[i]
    params = hyperparameters_dictionary[key]
    i += 1
    print(model)
    print(params)
    print('---------------------------------')

    classifier = GridSearchCV(model, params, cv=5)
    # fitting the data to classifier
    classifier.fit(x,y)
    result.append({
        'model used' : model,
        'highest score' : classifier.best_score_,
        'best hyperparameters' : classifier.best_params_
    })

  result_dataframe = pd.DataFrame(result, columns = ['model used','highest score','best hyperparameters'])
  return result_dataframe

In [136]:
ModelSelection(models_list, model_hyperparameters)

LogisticRegression(max_iter=10000)
{'C': [1, 5, 10, 20]}
---------------------------------
SVC()
{'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [1, 5, 10, 20]}
---------------------------------
KNeighborsClassifier()
{'n_neighbors': [3, 5, 10]}
---------------------------------
RandomForestClassifier(random_state=0)
{'n_estimators': [10, 20, 50, 100]}
---------------------------------

,model used,highest score,best hyperparameters
0,LogisticRegression(max_iter=10000),0.831585,{'C': 10}
1,SVC(),0.828306,"{'C': 1, 'kernel': 'linear'}"
2,KNeighborsClassifier(),0.643880,{'n_neighbors': 5}
3,RandomForestClassifier(random_state=0),0.838087,{'n_estimators': 100}